### ISSUE TITLE
安装出现SyntaxError: missing ) after argument list 报错

### ISSUE THREAD

**Issue by zengrd** [zhandouxiaojiji/behavior3editor#14]
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm ERR! code 1
npm ERR! path /Users/bytedance/Documents/github/behavior3editor/node_modules/electron
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! /Users/bytedance/Documents/github/behavior3editor/node_modules/yauzl/index.js:295
npm ERR!     buffer = newBuffer(entry.fileNameLength + entry.extraFieldLength + e
npm ERR!                                                                        ^
npm ERR! 
npm ERR! SyntaxError: missing ) after argument list
npm ERR!     at internalCompileFunction (node:internal/vm:73:18)
npm ERR!     at wrapSafe (node:internal/modules/cjs/loader:1176:20)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1218:27)
npm ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1117:32)
npm ERR!     at Module._load (node:internal/modules/cjs/loader:958:12)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1141:19)
npm ERR!     at require (node:internal/modules/cjs/helpers:110:18)
npm ERR!     at Object.<anonymous> (/Users/bytedance/Documents/github/behavior3editor/node_modules/extract-zip/index.js:8:15)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1254:14)
npm ERR! 
npm ERR! Node.js v18.16.0

**Comment by Binaryinject** [comment]
https://github.com/Binaryinject/behavior3editor/releases/tag/v0.1.11-alpha

**Comment by zhandouxiaojiji** [comment]
nodejs 切到v16版本可解决
