### ISSUE TITLE
关于nodejs版本

### ISSUE THREAD

**Issue by roiff** [zhandouxiaojiji/behavior3editor#15]
作者写着的nodejs版本需要16.20
我使用macos下使用arm芯片的macbook中，使用16.20会报错：ERR_OSSL_EVP_UNSUPPORTED
查询后是说16.20版本依赖openssl 3.0，导致webpack出错。
解决方法也很简单，把nodejs降级到16.13，问题解决。

特此说明下

**Comment by zhongfq** [comment]
> 作者写着的nodejs版本需要16.20 我使用macos下使用arm芯片的macbook中，使用16.20会报错：ERR_OSSL_EVP_UNSUPPORTED 查询后是说16.20版本依赖openssl 3.0，导致webpack出错。 解决方法也很简单，把nodejs降级到16.13，问题解决。
> 
> 特此说明下

升级了，可以使用最新的nodejs构建了
