### ISSUE TITLE
关于mac版的应用构建

### ISSUE THREAD

**Issue by roiff** [zhandouxiaojiji/behavior3editor#16]
因为js代码我也不太熟悉，以下只是给出了临时解决方案，让他可以构建出macos上的应用。
1.找到项目根目录 package.json文件
第10行代码改为
"dist": "npm run prestart && electron-builder --dir && electron-builder --mac"

2.找到目录main-process下的Settings.ts文件
在文件头部加入两行
import { app } from 'electron';
import path from 'path';

然后找到以下这行代码
const settingPath = "settings.json";
注释这行代码，增加两行，如下所示
// const settingPath = "settings.json";
const userDataPath = app.getPath('userData');
const settingPath = path.join(userDataPath, 'settings.json');

然后运行 npm run dist即可，会在build中找到响应的应用

我是mac arm64的m系列芯片，使用electron-builder --mac没有问题，我不知道如果是intel的机器，这个地方是否需要更改

就不推送代码了，太简陋了，如果作者有时间，可以考虑下mac下的应用构建。

**Comment by zhongfq** [comment]
> 因为js代码我也不太熟悉，以下只是给出了临时解决方案，让他可以构建出macos上的应用。 1.找到项目根目录 package.json文件 第10行代码改为 "dist": "npm run prestart && electron-builder --dir && electron-builder --mac"
> 
> 2.找到目录main-process下的Settings.ts文件 在文件头部加入两行 import { app } from 'electron'; import path from 'path';
> 
> 然后找到以下这行代码 const settingPath = "settings.json"; 注释这行代码，增加两行，如下所示 // const settingPath = "settings.json"; const userDataPath = app.getPath('userData'); const settingPath = path.join(userDataPath, 'settings.json');
> 
> 然后运行 npm run dist即可，会在build中找到响应的应用
> 
> 我是mac arm64的m系列芯片，使用electron-builder --mac没有问题，我不知道如果是intel的机器，这个地方是否需要更改
> 
> 就不推送代码了，太简陋了，如果作者有时间，可以考虑下mac下的应用构建。

已经搞定mac的构建了
