### ISSUE TITLE
关于node配置的问题

### ISSUE THREAD

**Issue by GeorgeShiZZZ** [zhandouxiaojiji/behavior3editor#20]
可以增加一个像以前一样选择配置节点的功能吗？多个文件在一起开发存在多个配置节点的问题，把节点合并，又得解决重名问题。希望作者大大，可以增加一个像以前一样选择配置节点的功能。

**Comment by zhongfq** [comment]
就是以前那个选择配置的功能？

**Comment by zhandouxiaojiji** [comment]
不同节点定义的行为树，理论上应该新建不同的工程吧？如果是每打开一个行为树还要重新选择一次节点配置，可能不是个好主意，很容易出错

**Comment by GeorgeShiZZZ** [comment]
> 不同的节点定义的行为树，理论上应该新建不同的工程吧？如果是每打开一个行为树都要重新选择一次节点配置，可能不是个好主意，很容易出错

赞同大大的设计，设计上确实这样更合理。但是实际写行为树的过程中，可能遇到一个项目多配置，举个例子，MMO多职业，每一个职业会有对应的node文件，想同时编辑就很繁琐，特别像mac这种不支持electron多开的情况下，会变得很麻烦。

**Comment by GeorgeShiZZZ** [comment]
> 就是以前那个选择配置的功能吗？
是的，大大

**Comment by zhongfq** [comment]
> > 不同的节点定义的行为树，理论上应该新建不同的工程吧？如果是每打开一个行为树都要重新选择一次节点配置，可能不是个好主意，很容易出错
> 
> 赞同大大的设计，设计上确实这样更合理。但是实际写行为树的过程中，可能遇到一个项目多配置，举个例子，MMO多职业，每一个职业会有对应的node文件，想同时编辑就很繁琐，特别像mac这种不支持electron多开的情况下，会变得很麻烦。

目前支持多开。。。所以好像你的问题，也不是问题了

**Comment by zhongfq** [comment]
> > 不同的节点定义的行为树，理论上应该新建不同的工程吧？如果是每打开一个行为树都要重新选择一次节点配置，可能不是个好主意，很容易出错
> 
> 赞同大大的设计，设计上确实这样更合理。但是实际写行为树的过程中，可能遇到一个项目多配置，举个例子，MMO多职业，每一个职业会有对应的node文件，想同时编辑就很繁琐，特别像mac这种不支持electron多开的情况下，会变得很麻烦。

这种建议你直接新建多个项目，现在windows mac都支持多开

**Comment by GeorgeShiZZZ** [comment]
看到了，不好意思，谢谢大大。最后提一个小优化，常量参数 传值为bool类型时，可以默认为false，这样新建的时候就可以不用再去开关一下。最后还是谢谢大大们。

**Comment by GeorgeShiZZZ** [comment]
看到了，不好意思，谢谢大大。最后提一个小优化，常量参数 传值为bool类型时，可以初始默认为false，这样新建的时候就可以不用再去开关一下。最后还是谢谢大大们。
![123](https://github.com/zhandouxiaojiji/behavior3editor/assets/82556182/7a684691-7322-4583-904d-c66115a2ee19)

**Comment by zhongfq** [comment]
> 看到了，不好意思，谢谢大大。最后提一个小优化，常量参数 传值为bool类型时，可以初始默认为false，这样新建的时候就可以不用再去开关一下。最后还是谢谢大大们。 ![123](https://private-user-images.githubusercontent.com/82556182/323827790-7a684691-7322-4583-904d-c66115a2ee19.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MDA3ODQsIm5iZiI6MTcxMzUwMDQ4NCwicGF0aCI6Ii84MjU1NjE4Mi8zMjM4Mjc3OTAtN2E2ODQ2OTEtNzMyMi00NTgzLTkwNGQtYzY2MTE1YTJlZTE5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDA0MjEyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2NmMyM2JmZDU5MmIzNjhjZmFiYWUzZjk5MmUyY2VlOTE5ODhkNjhkNWFmNGU1OTFlNGQ0N2M0N2Q4YzM0YWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MYFKIgoOtfxzagsiJ1wd-T2kZZQyhnHdRS3Rh0_j5S0)

行，下次更新优化一下
