### ISSUE TITLE
节点搜索

### ISSUE THREAD

**Issue by GeorgeShiZZZ** [zhandouxiaojiji/behavior3editor#21]
大大，有考虑过做一个节点搜索的功能吗？树太大以后真的很难定位。

**Comment by zhongfq** [comment]
先考虑一下，看一下怎么做合理

**Comment by zhongfq** [comment]
https://github.com/zhandouxiaojiji/behavior3editor/releases/tag/v1.1.3

**Comment by GeorgeShiZZZ** [comment]
谢谢大大，稍稍提个优化，我觉得查询的input上加个回车事件就更好了，然后过滤节点的时候大概率不会去查询节点的方法名称，可以把desc加入过滤的list中，感觉这样更好一点。emmm其实我感觉name,desc,input,agrs,output,path其实都应该在搜索队列里。

**Comment by zhongfq** [comment]
> 谢谢大大，稍稍提个优化，我觉得查询的input上加个回车事件就更好了，然后过滤节点的时候大概率不会去查询节点的方法名称，可以把desc加入过滤的list中，感觉这样更好一点。emmm其实我感觉name,desc,input,agrs,output,path其实都应该在搜索队列里。

用回车事件触发搜索，普通 输入不触发？

**Comment by GeorgeShiZZZ** [comment]
我的意思是回车事件触发跳转下一个，就是在调用下向下的那个方法，就和vscode一样

**Comment by GeorgeShiZZZ** [comment]
const handleKeyPress = (event: any) => {
    if (event.key === 'Enter') {
      if (results.length > 0) {
        const idx = ( resultIndex + 1 ) % results.length
        setResultIndex(idx)
        editor.graph.focusItem(results[idx])
        selectNode(results[idx])
      }
    }
  }

**Comment by zhongfq** [comment]
> onKeyPress={ handleKeyPress } const handleKeyPress = (event: any) => { if (event.key === 'Enter') { if (results.length > 0) { const idx = ( resultIndex + 1 ) % results.length setResultIndex(idx) editor.graph.focusItem(results[idx]) selectNode(results[idx]) } } } 大概就这个意思

你可以拉测试分支，自己编译试一下

**Comment by zhongfq** [comment]
> 可以了大大，很完美，先膜拜一下。大大，filterNodes方法，是否应该是组合判断，不然只能单独判断一种形式的参数，最后可以加一个node.id的过滤，只是提供建议，大大可以参考下。 ![2222](https://private-user-images.githubusercontent.com/82556182/326327381-0a38b060-ac0b-4d69-a1db-931531e9302a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNzA1NjksIm5iZiI6MTcxNDM3MDI2OSwicGF0aCI6Ii84MjU1NjE4Mi8zMjYzMjczODEtMGEzOGIwNjAtYWMwYi00ZDY5LWExZGItOTMxNTMxZTkzMDJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDA1NTc0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmNDUzZmRiZGY0YmU3N2I1NmQ1YzM5MjgxOWQ3YzBlYTg0MDQzODhjOTQ0NmEzYTNkZDFlYmJlYWU3ZWRjMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M-5L5MRfojpFeGprCCZeofxuWtfjX8iRoNzg_ffR8ho)

你可以提个PR，我测试一下

**Comment by zhongfq** [comment]
> 可以了大大，很完美，先膜拜一下。大大，filterNodes方法，是否应该是组合判断，不然只能单独判断一种形式的参数，最后可以加一个node.id的过滤，只是提供建议，大大可以参考下。 ![2222](https://private-user-images.githubusercontent.com/82556182/326327381-0a38b060-ac0b-4d69-a1db-931531e9302a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNzA1NjksIm5iZiI6MTcxNDM3MDI2OSwicGF0aCI6Ii84MjU1NjE4Mi8zMjYzMjczODEtMGEzOGIwNjAtYWMwYi00ZDY5LWExZGItOTMxNTMxZTkzMDJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDA1NTc0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmNDUzZmRiZGY0YmU3N2I1NmQ1YzM5MjgxOWQ3YzBlYTg0MDQzODhjOTQ0NmEzYTNkZDFlYmJlYWU3ZWRjMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M-5L5MRfojpFeGprCCZeofxuWtfjX8iRoNzg_ffR8ho)

组合判断没有太大的意义，我们搜索的是节点而已，不需要高亮显示内容，所以只需要有一个满足就行了

**Comment by zhongfq** [comment]
> 可以了大大，很完美，先膜拜一下。大大，filterNodes方法，是否应该是组合判断，不然只能单独判断一种形式的参数，最后可以加一个node.id的过滤，只是提供建议，大大可以参考下。 ![2222](https://private-user-images.githubusercontent.com/82556182/326327381-0a38b060-ac0b-4d69-a1db-931531e9302a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNzEyNDEsIm5iZiI6MTcxNDM3MDk0MSwicGF0aCI6Ii84MjU1NjE4Mi8zMjYzMjczODEtMGEzOGIwNjAtYWMwYi00ZDY5LWExZGItOTMxNTMxZTkzMDJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDA2MDkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwZWQ5NWEwZjc3ZDk5OTE1OTdmODYxNmRjZDY2ODZmMzVlOGE2ZDdlYzFiNWVjMGU0NGZkZjhlNWRhNjYxOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q0JqX99EbxWd5__POPgsqgyE3h-fibQfIxtWU5azDws)

组合判断没有太大的意义，我们搜索的是节点而已，不需要高亮显示内容，所以只需要有一个满足就行了

另外要包含id的判断，你可以提一个PR，我测试一下

**Comment by GeorgeShiZZZ** [comment]
大大们，给个权限。

**Comment by GeorgeShiZZZ** [comment]
大大，没权限算了，提供个思路，就是共用一个搜索框，ctrl+f搜索正常参数，ctrl+g搜索节点。这样可以不用很多代码，就实现id查询。

**Comment by zhongfq** [comment]
> 大大们，给个权限。

提PR不用权限吧。。。

**Comment by zhongfq** [comment]
> 大大们，给个权限。

提PR不用权限的啊，在你的fork的仓库实现好，然后使用create pull request，提到上游仓库
