### ISSUE TITLE
关于linux如何构建编辑器

### ISSUE THREAD

**Issue by donneyluck** [zhandouxiaojiji/behavior3editor#27]
感谢大佬的作品
有linux下编辑的需求 请问如何构建linux的可执行版本
没有相关的build文档

**Comment by GeorgeShiZZZ** [comment]
electron自身就提供linux版本,在linux环境下,编译对应环境的包,就可以用了.具体可以看一下electron文档https://www.electronjs.org/zh/docs/latest/development/build-instructions-linux
