### ISSUE TITLE
老版本的electron不支持苹果m1

### ISSUE THREAD

**Issue by zhandouxiaojiji** [zhandouxiaojiji/behavior3editor#7]
计划升级最新版electron

**Comment by cloudfreexiao** [comment]
升级了下  mac 系统 12.4 启动报错
`
        electron_1.nativeTheme.themeSource = "dark";
                                           ^
TypeError: Cannot set property 'themeSource' of undefined
`

**Comment by zhandouxiaojiji** [comment]
@cloudfreexiao 最近的pr #8 已升级electron，支持m1的最新系统

**Comment by cloudfreexiao** [comment]
可以了 多谢～～
